name: Build & Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/doenerguide:latest
  deploy_via_ssh:
    needs: docker
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: copy files to target server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/doenerguide/"
      - name: Run remote docker pull
        uses: appleboy/ssh-action@master
        env:
          APPTOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: APPTOKEN, USERNAME
          script: |
            echo $APPTOKEN | docker login -u $USERNAME --password-stdin
            cd ~/doenerguide
            docker-compose -f ~/doenerguide/docker-compose.yml pull
            docker-compose -f ~/doenerguide/docker-compose.yml up backend -d
