name: Frontend CI/CD workflow

on:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        working-directory: ./doenerguide
        run: npm install

      - name: Lint code
        working-directory: ./doenerguide
        run: npm run lint
